package seq2linq

import (
	"iter"

	"github.com/solsw/errorhelper"
)

// InfiniteSequence generates an infinite sequence of pairs of values that begins
// with 'startK' and 'startV' and yields additional pairs of values generated by 'next'.
func InfiniteSequence[K, V any](startK K, startV V, next func(prevK K, prevV V) (K, V)) (iter.Seq2[K, V], error) {
	if next == nil {
		return nil, errorhelper.CallerError(ErrNilNext)
	}
	return func(yield func(K, V) bool) {
			k := startK
			v := startV
			for {
				if !yield(k, v) {
					return
				}
				k, v = next(k, v)
			}
		},
		nil
}
